set-option -g prefix M-w
unbind C-b
bind-key M-w send-prefix

set -g default-shell ${SHELL}
set -g default-command ${SHELL}

# Open a new window with the current directory of the current pane
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g mouse on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:RGB"

set -g status-position top

set -g focus-events on

set -sg escape-time 0

set -g history-limit 5000

# remove confirmation when killing
bind-key & kill-window
bind-key x kill-pane
